### ISSUE TITLE
Strukturerte feilkoder

### ISSUE THREAD

**Issue by joergenb** [digdir/roadmap#1]
Frå NHN:

Vi øsnker å få returnert en ny property error_code (eller lignende) som har en egen error kode for de tekstlige feilmeldingene fra Maskinporten. Dette er fordi vi ønsker å behandle disse feilene i vårt system og da er vi avhengig av at vi kan få en unik kode, så om teksten (error_description) endrer seg så vil ikke det påvirke koden vår.

```[tasklist]
### oppgåver:
- [ ] felleslosninger/maskinporten/issues/307 
- [ ] https://github.com/felleslosninger/maskinporten/issues/311
```

**Comment by bestrand** [comment]
Tasks:
- [ ] https://github.com/felleslosninger/maskinporten/issues/307

**Comment by bestrand** [comment]
```[tasklist]
### Tasklist (private beta)
- [ ] https://github.com/felleslosninger/maskinporten/issues/307
```

**Comment by bestrand** [comment]
#### Tasklists (private beta)

```[tasklist]
### Tasks
- [ ] https://github.com/felleslosninger/maskinporten/issues/307
```

**Comment by bestrand** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/felleslosninger/maskinporten/issues/307
```

**Comment by bestrand** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/felleslosninger/maskinporten/issues/307
- [ ] https://github.com/felleslosninger/maskinporten/issues/311
```

**Comment by joergenb** [comment]
Ein oversikt over gjeldande feilkoder finn du her: https://maskinporten.no/errors/
og litt meir utfyllande info her: https://docs.digdir.no/docs/Maskinporten/maskinporten_feilsoking
