### ISSUE TITLE
Forbedret dokumentasjon

### ISSUE THREAD

**Issue by RonnyB71** [digdir/roadmap#125]
Vi har mye dokumentasjon, men den oppleves som vanskelig å finne frem i for tjenesteutviklere.

```[tasklist]
### Tasks
- [ ] Gjennomgang av strukturen og etablere ny struktur med fokus hva man ønsker å få gjort fremfor en speiling av teknisk implementering
- [ ] Identifisering av områder som trenger mer omfattende eksempler
- [ ] Kobling av løsning direkte mot dokumentasjon slik at man i Studio får direkte lenker til relevant dokumentasjon
- [ ] Trekke frem flere reelle eksempler på hvordan løse konkrete oppgaver
```

**Comment by Ildest** [comment]
Etter avtale med @nkylstad tenkte jeg å lage en underoppgave her, for å bruke KI til å analysere og foreslå struktur og analysere duplikater og utdatert dok. Men jeg ser at jeg ikke har tilgang til å opprette noe på denne saken (det skal vi kanskje ikke gjøre heller?), så jeg lager en i tavla til Utforming, og lenker til veikartsaken.
