### ISSUE TITLE
Utviklingsarbeid Dialogporten

### ISSUE THREAD

**Issue by SnorreTE** [digdir/roadmap#163]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten/issues/29
- [ ] https://github.com/digdir/dialogporten/issues/33
- [ ] https://github.com/digdir/dialogporten/issues/36
- [ ] https://github.com/digdir/dialogporten/issues/41
- [ ] https://github.com/digdir/dialogporten/issues/45
- [ ] https://github.com/digdir/dialogporten/issues/48
- [ ] https://github.com/digdir/dialogporten/issues/53
- [ ] https://github.com/digdir/dialogporten/issues/55
- [ ] https://github.com/digdir/dialogporten/issues/57
```

**Comment by elsand** [comment]
Denne fjernes til fordel for andre roadmap-issues som granulerer dette annerledes.
