### ISSUE TITLE
Involvering av SBS-leverandører

### ISSUE THREAD

**Issue by SnorreTE** [digdir/roadmap#165]
## Overordnet beskrivelse

For å sikre god forankring hos sluttbrukersystemleverandørene må disse involveres i realiseringen av Dialogporten

## Forventet resultat

Vi har på plass et fåtall med systemleverandører som har tatt implementert en tjeneste som er realisert på Dialogporten

## Hvordan vil det virke?
Det er enkelt for SBS leverandører å onboarde og finne informasjon om Dialogporten.
SBS Leverandører får tilbud om informasjonsmøter/webinar slik at de har muloighet for å holde seg oppdatert
Dokumentasjon for onboarding av SBS lev er på plass

```[tasklist]
### Tasks
- [x] se alle issues i backlog for status
- [x] Webinarrekke etableres for SBS leverandører av marked
- [x] Vi lager eget webinar der vi også omtaler onboarding
- [x] Dokumentasjon for onboarding for SBS leverandører etableres
- [x] Onboarding dokumentasjon publiseres på Samarbeidsportalen
- [x] Vi har opprettet en Slack kanal for support henvendelser direkte til teamet
- [x] Servicedesk opptar DP inn i sine rutiner
```

```[tasklist]
### Avhengigheter
```

**Comment by DirkLammering** [comment]
Denne er forsovet lukket i Milestones arket - vi beholder den her for å beholde fokus men selve aktiviteten er overført til amrkedsgruppen som aktivt involverer SBS leverandørene. Videre har SKE allerede involvert noen av de største SBS leverandørene i piloten sin.
