### ISSUE TITLE
Etablering av teknisk forvaltning og drift

### ISSUE THREAD

**Issue by SnorreTE** [digdir/roadmap#167]
## Overordnet beskrivelse

Det skal etableres et regime for drift og teknisk forvaltning av Dialogporten

## Forventet resultat

Produktet skal i produksjonsmiljøet kjøre med høy tilgjengelighet, sikkerhet og forutsigbart kostnadsnivå

## Hvordan vil det virke?

Det etableres mekanismer og rutiner for hendeleshåndtering, samt monitorering som muliggjør en pro-aktiv drift, og mulighet for uthenting av statistikk for både tekniske og merkantile formål.

### Tasks
- [ ] https://github.com/digdir/dialogporten/issues/74
- [ ] https://github.com/digdir/dialogporten/issues/79
- [ ] https://github.com/digdir/dialogporten/issues/164
