### ISSUE TITLE
Definer løsningskonsept for arbeidsflaten (Del A)

### ISSUE THREAD

**Issue by LisLonning** [digdir/roadmap#185]
## Overordnet beskrivelse
Løsningskonseptet bygger på reell innsikt og skal i tilstrekkelig grad imøtekomme og balansere behovene (mennesklige, tekniske og forretningsmessige) konseptet bygger på.

## Forventet resultat
Et validert løsningskonsept som har god dekning for- og balansegang mellom behovene.

## Hvordan skal det fungere?
Under planlegging av den konseptuelle brukertesten vil det settes måleenheter for å vurdere grad av oppfyllelse rundt behov.

### Avhengigheter
Ingen avhengigheter identifisert

```[tasklist]
### Oppgaver
- [ ] digdir/dialogporten-frontend-react/issues/42
- [ ] digdir/dialogporten-frontend-react/issues/12
- [ ] digdir/dialogporten-frontend-react/issues/14
```

**Comment by indiamaydesign** [comment]
@MetteSaltnes as discussed closing this issue as the first concept for testing has been delivered, and further scoped milestones and epics in the roadmap will reflect iteration and ongoing solution changes

**Comment by sorensensig** [comment]
Lukker oppgaven som **levert** etter ønske fra @indiamaydesign.

**Comment by indiamaydesign** [comment]
Placeholder: Link to presentation issue in Dialogporten-frontend should go here once done or in issue description
