### ISSUE TITLE
Definer løsningskonsept for arbeidsflaten (Del B)

### ISSUE THREAD

**Issue by sorensensig** [digdir/roadmap#186]
## Overordnet beskrivelse
Løsningskonseptet bygger på reell innsikt og skal i tilstrekkelig grad imøtekomme og balansere behovene (mennesklige, tekniske og forretningsmessige) konseptet bygger på.

## Forventet resultat
Et validert løsningskonsept som har god dekning for- og balansegang mellom behovene.

## Hvordan skal det fungere?
Under planlegging av den konseptuelle brukertesten vil det settes måleenheter for å vurdere grad av oppfyllelse rundt behov.

### Avhengigheter
Ingen avhengigheter identifisert

```[tasklist]
### Oppgaver
- [ ] digdir/dialogporten-frontend-react/issues/25
- [ ] digdir/dialogporten-frontend-react/issues/15
- [ ] digdir/dialogporten-frontend-react/issues/17
```
