### ISSUE TITLE
Integrasjon med Altinn Events PoC

### ISSUE THREAD

**Issue by elsand** [digdir/roadmap#200]
## Overordnet beskrivelse

Dialogporten skal produsere events på vegne av tjenesteeierne ved opprettelse og endring av dialoger.

## Forventet resultat

Det er tilrettelagt for hendelsbaserte integrasjoner med Dialogporten som reduserer behovet for polling og legger til rette for sammenhengende tjenester med at andre tjenesteeiere kan lytte på events og potensielt trigge relaterte tjenestekjeder.

**For PoC leveres en løsning med full funksjonelle kapabilitet, men som mangler skaleringsmulighetene som skal realiseres med #312** 

## Hvordan vil det virke?

Dialogporten vil automatisk produsere en rekke ulike typer events som følger et fast mønster. Disse eventene skal være gjenstand for autoriasjon på samme måte som dialogen i seg selv, og det skal følgelg være mulig for både sluttbrukere og andre offentlige virksomheter å konsumere events for en gitt tjeneste utfra den definerte policyen

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten/issues/48
```

```[tasklist]
### Avhengigheter
- [ ] https://github.com/altinn/altinn-events/issues/311
- [ ] https://github.com/altinn/altinn-events/issues/159
- [ ] https://github.com/altinn/altinn-events/issues/247
```
