### ISSUE TITLE
Integrere med Altinn 3 tjenesteplattform

### ISSUE THREAD

**Issue by elsand** [digdir/roadmap#202]
## Overordnet beskrivelse

Dialogporten skal ha en representasjon av alle instanser av apper i Altinn 3.

## Forventet resultat

Brukere kan benytte sluttbrukerløsninger over Dialogporten, f.eks. felles arbeidsflate, for å finne pågående og avsluttede app-instanser i Altinn 3. 

## Hvordan vil det virke?

Det etableres en platform-komponent som sørger for å synkronisere appinstans-data med dialoger i Dialogporten. Dette skal skje transparent for tjenesteeier.

### Tasks
- [x] https://github.com/digdir/dialogporten/issues/55

### Avhengigheter
- [ ] https://github.com/Altinn/altinn-storage/issues/665
- [x] https://github.com/Altinn/altinn-register/issues/233
- [x] https://github.com/Altinn/altinn-authorization-tmp/issues/88
- [x] https://github.com/Altinn/altinn-events/issues/653
- [x] https://github.com/Altinn/altinn-authorization/issues/1084 (mangler implementeringsoppgave)
