### ISSUE TITLE
Formidlingstjenesten - Nytt Api for avsendere

### ISSUE THREAD

**Issue by leogasnier** [digdir/roadmap#216]
### **Overordnet beskrivelse**
Api som erstatter altinn 2 apiene klart til bruk.

**Forventet resultat**
Legge til rette for at avsendere og konsumenter kan starte flytting til nye apier.

**Hvordan skal det fungere?**

(https://github.com/Altinn/altinn-broker/blob/main/altinn-broker-v1.json)

https://docs.altinn.studio/broker/

Gjennomføring

```[tasklist]
### Avhengigheter
- [ ] https://github.com/digdir/roadmap/issues/191
```

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/83
- [ ] https://github.com/Altinn/altinn-broker/issues/135
- [ ] https://github.com/Altinn/altinn-broker/issues/134
```
