### ISSUE TITLE
Oppsett og test av formidlingstjeneste i ny løsning

### ISSUE THREAD

**Issue by leogasnier** [digdir/roadmap#219]
### **Overordnet beskrivelse**
Tjenester kan defineres i Altinn 3 og testes.

**Forventet resultat**
Tjenesteeiere kan definere og konfigurere formidlingstjenester.

**Hvordan skal det fungere?**
Altinn studio

**Gjennomføring**
TBD

```[tasklist]
### Avhengigheter
- [ ] https://github.com/digdir/roadmap/issues/201
- [ ] https://github.com/digdir/roadmap/issues/191
```

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/76
```
