### ISSUE TITLE
Etablering ny fellesløsning (eSignering)

### ISSUE THREAD

**Issue by sramung** [digdir/roadmap#291]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/roadmap/issues/329
- [ ] https://github.com/digdir/roadmap/issues/330
- [ ] https://github.com/digdir/roadmap/issues/328
- [ ] https://github.com/digdir/roadmap/issues/32
```
