### ISSUE TITLE
Integrasjon med Altinn Events for pilot/full produksjon

### ISSUE THREAD

**Issue by elsand** [digdir/roadmap#312]
## Overordnet beskrivelse

Dialogporten skal produsere events på vegne av tjenesteeierne ved opprettelse og endring av dialoger på en robust måte som skalerer til store trafikkmengder

## Forventet resultat

Funksjonelle kapabiliteter leveres i #200, men muligheten til å skalere opp til produksjonsnivåer på trafikk krever annen infrastruktur. Dette vil leveres i denne perioden.

## Hvordan vil det virke?

Dialogporten vil automatisk produsere en rekke ulike typer events som følger et fast mønster. Disse eventene skal være gjenstand for autoriasjon på samme måte som dialogen i seg selv, og det skal følgelg være mulig for både sluttbrukere og andre offentlige virksomheter å konsumere events for en gitt tjeneste utfra den definerte policyen

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten/issues/48
```

```[tasklist]
### Avhengigheter
- [ ] https://github.com/altinn/altinn-events/issues/311
- [ ] https://github.com/altinn/altinn-events/issues/159
- [ ] https://github.com/altinn/altinn-events/issues/247
```
