### ISSUE TITLE
Varsling - Profil - integrasjon og replikering - Offentlig Varslingsinformasjon for Virksomheter

### ISSUE THREAD

**Issue by olebhansen** [digdir/roadmap#408]
## Forventet resultat
* Altinn3 har en kopi av Offentlig Varslingsregister for Virksomheter som holdes kontinuerlig oppdatert. 
* API for oppslag er tilgjengelig for interne konsumenter.
* Varsling til virksomheter i Altinn3 benytter Altinn3-kopi som kilde for virksomhetsinformasjon

## Hvordan skal det fungere?
Etablering av en ny uavhengig kopi. Initiell datalast og periodisk synkronisering av endringer til kopi.

Dette legger til rette for visning av kontaktinformasjon i Arbeidsflate under profil (innkommende avhengighet til dette veikartelementet)

### Tasks
- [ ] https://github.com/Altinn/altinn-profile/issues/200 *
- [ ] https://github.com/Altinn/altinn-profile/issues/201 *
- [ ] TBD: endring av varsel for å gjøre oppslag (usikkert om dette er ideelt, siden informasjonen uansett må hentes fra Altinn2 ifm. å finne egendefinert kontaktinfo - se #411 )
- [ ] TBD: Endringer i Altinn2 for å route skriv/les fra Altinn3 sin "kopi" - ikke relevant før tidligst når arbeidsflate har et GUI, om noen gang.

\* part of epic https://github.com/Altinn/altinn-profile/issues/177, but listed individually for more granular visibility
