### ISSUE TITLE
Styrings- og forvaltningsregime for Peppol eGovernment

### ISSUE THREAD

**Issue by steinarhenriksen** [digdir/roadmap#56]
```[tasklist]
### Tasks
- [x] Etablere teknisk dokumentasjon for Peppol eGovernment på Digdir Docs
- [x] Etablere sider for Peppol eGovernment på Digdir Docs
- [x] Side med informasjon om forvaltningsregimet
- [x] Side for onboarding av leverandører
- [x] Side for onboarding av virksomheter
- [x] Side for kostnader
```
